[book]
title = "RDB Documentation"
authors = ["Muhammad Fiaz"]
language = "en"
src = "src"

[build]
build-dir = "../target/docs"
create-missing = true
extra-watch-dirs = []

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/muhammad-fiaz/RDB"
edit-url-template = "https://github.com/muhammad-fiaz/RDB/edit/main/docs/{path}"
site-url = "https://muhammad-fiaz.github.io/RDB/"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
